add translations. BSFER-127 WIP
camptocamp/odoo-event-addons pull request #18
Opened 2018-05-23 14:18 UTC by tschanzt

2018-05-25 15:25 UTC, tschanzt commented
@simahawk just so you don't forget this pr exists as well.(also mentioned on the card)

2018-05-28 09:31 UTC, simahawk requested changes
I'm on it for fixes.
Also, the pending merge of this PR was not included.

2018-05-28 09:31 UTC, simahawk commented on event_lead_event/static/src/js/fix_translations.js
> +odoo.define('event_lead_event.fix_translations', function (require) {
AFAIK this is not needed at all

2018-05-28 09:39 UTC, simahawk approved these changes

2018-05-28 09:47 UTC, merged