add event_autotrack module
camptocamp/odoo-event-addons pull request #2
Opened 2018-02-13 10:01 UTC by tschanzt

This adds a module to automaticly create a track when an event is created.

2018-02-13 10:05 UTC, simahawk requested changes
Also, README missing. See here https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'description': "Automaticly create tracks.",
check spelling

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'description': "Automaticly create tracks.",
`description` is deprecated use `summary`

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'version': '1.0',
11.0.1.0.0

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'author': 'Camptocamp',
include OCA, see https://github.com/OCA/maintainer-tools/tree/master/template/module

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'website': 'http://www.camptocamp.com',
https://github.com/camptocamp/odoo-event-addons

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> +    ],
fix indent

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/__manifest__.py
> + 'data': [],
drop data

2018-02-13 10:05 UTC, simahawk commented on event_autotrack/tests/test_autotrackevent.py
> +from odoo.tests.common import SavepointCase
import this file in tests/__init__.py otherwise odoo won't run it

2018-02-13 15:24 UTC, tschanzt commented
@simahawk i updated the pullrequest.

2018-02-14 08:21 UTC, simahawk commented
@tschanzt as per our chat: pls rename this module to `event_default_track`

2018-02-14 10:41 UTC, tschanzt commented
@simahawk name is changed.

2018-02-15 09:46 UTC, simahawk commented
cleaned up and merged.
@tschanzt note that I had to fix README -> is rst, not md ;)

2018-02-15 09:46 UTC, closed without merging