Create module website_event_questions_open_ended
camptocamp/odoo-event-addons pull request #21
Opened 2018-07-17 08:42 UTC by grindtildeath

2018-07-17 09:16 UTC, tschanzt approved these changes

2018-07-17 10:19 UTC, ghost approved these changes
LGTM w/ some nitpicking remarks :slightly_smiling_face:

2018-07-17 10:19 UTC, ghost commented on website_event_questions_open_ended/models/__init__.py
> +from . import event
newline

2018-07-17 10:19 UTC, arkostyuk commented on website_event_questions_open_ended/__manifest__.py
> +        'views/event_views.xml'
comma

2018-07-17 10:19 UTC, arkostyuk commented on website_event_questions_open_ended/models/event.py
> +    question_id = fields.Many2one('event.question', required=True,
would be nice to have those params on a dedicated line each :)

2018-07-17 10:19 UTC, arkostyuk commented on website_event_questions_open_ended/__manifest__.py
> +    'installable': True,
default?

2018-07-25 10:22 UTC, simahawk requested changes

2018-07-25 10:22 UTC, simahawk commented on website_event_questions_open_ended/security/ir.model.access.csv
> +event_answer_open_all,event.answer.open.all,model_event_answer_open,,1,1,1,0
no one can unlink?
You should have some event groups

2018-07-25 13:19 UTC, simahawk requested changes

2018-07-25 13:19 UTC, simahawk commented on website_event_questions_open_ended/controllers/main.py
> +            WebsiteEvent, self)._process_registration_details(details)
due to the black magic inheritance of odoo controllers: when you inherit them too much you have such issues.
Try this:
```python
question_controller = WebsiteEvent()
registrations = question_controller._process_registration_details(details)
```

2018-07-25 13:21 UTC, simahawk requested changes

2018-07-25 13:21 UTC, simahawk commented on website_event_questions_open_ended/controllers/main.py
> +                        'question_id': key[13:],
:open_mouth: no better way to slice this key?
`key.split('open-answers-')[-1]`?

2018-07-26 07:30 UTC, simahawk approved these changes

2018-07-26 07:31 UTC, merged